---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groups-server-01
  name: groups-server-01
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: groups-server-01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app: groups-server-01
    spec:
      containers:
      - env:
        image: groupsinfra/groups-server:groups-4.3.groups-4.3.0.a6592278.714.1474.1683
        args: ["--headless","--public", "--dedicated", "--max_retries", "100", "--map", "uro://b32aa3d8-6913-43e0-bc95-2dd1947c325a",
          "--server_name", "V-Sekai Preview TPS Demo", "--port", "7803"]
        imagePullPolicy: IfNotPresent
        name: groups-server-01
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
