#!/usr/bin/env python

import os

Import("env")

env_motion_matching = env.Clone()
if not env.msvc:
    env_motion_matching.Append(CCFLAGS=["-Wno-error=non-virtual-dtor"])
    env_motion_matching.Append(CCFLAGS=["-Wno-error=ctor-dtor-privacy"])

env_motion_matching.Prepend(CPPPATH=["#modules/motion_matching/thirdparty/motionmatchingboost"])
env_motion_matching.add_source_files(env.modules_sources, "*.cpp")
env_motion_matching.add_source_files(env.modules_sources, "src/*.cpp")
env_motion_matching.add_source_files(env.modules_sources, "thirdparty/*.cpp")

if env.editor_build:
    env_motion_matching.add_source_files(env.modules_sources, "editor/*.cpp")
